steps:
  - name: gradle:7.5-jdk21
    entrypoint: bash
    args:
      - -c
      - |
        ./gradlew clean bootJar

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/streamtool'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/streamtool'